### ISSUE TITLE
Feedback on the extension :) 

### ISSUE THREAD

**Issue by benja-M-1** [KWasm/kwasm-docker-extension#1]
Hi 👋 

I installed the extension to try it out; here is some feedback:
- every link opens within Docker Desktop. There is an SDK method to open links in a browser: https://docs.docker.com/desktop/extensions-sdk/dev/api/dashboard/#open-a-url
- I didn't know what was happening when clicking on "Install Spin". I would be good to have a progress indicator and disable the button maybe

I didn't use it further because I don't know how to use wasm. Having examples of what to do next would be great for people to try out.

Hope all of that makes sense.
Best,
Ben

**Comment by 0xE282B0** [comment]
Makes total sense, I just published a 0.2.0 version. Still hacky but with `openExternal(...)` and feedback with the next steps after successful installation.

**Comment by benja-M-1** [comment]
Closing since you made it :)
